In [3]:
from bam_gym.envs import custom_spaces

import gymnasium as gym
from gymnasium import spaces
import numpy as np

In [31]:
action_space = spaces.Box(low=-1, high=1, shape=None, dtype=np.float32)

action_space.seed(1)
for i in range(10):
    print(action_space.sample())


[0.02364325]
[0.90092736]
[-0.71168077]
[0.8972989]
[-0.37633708]
[-0.1533471]
[0.65540516]
[-0.18160173]
[0.09918737]
[-0.9448818]


In [23]:
action_space = spaces.Sequence(spaces.Box(low=-1, high=1, shape=None, dtype=np.float32))
action_space.sample(mask=(2,None))

(array([0.6273108], dtype=float32), array([0.240238], dtype=float32))

In [9]:
action_space = spaces.Sequence(spaces.Box(low=-1, high=1, shape=(5,), dtype=np.float32))
action_space.sample(mask=(2,None))

(array([ 0.92676854,  0.23504135, -0.622062  , -0.01817277, -0.34372887],
       dtype=float32),
 array([-0.15287939, -0.26875708,  0.9184532 , -0.94524306, -0.21889484],
       dtype=float32))

In [4]:
observation_dict = spaces.Dict({})
observation_dict["obs_names"] = spaces.Sequence(spaces.Text(max_length=32))
observation_dict["obs"] = spaces.Sequence(spaces.Box(low=-1, high=1, shape=None, dtype=np.float32))

In [11]:
mask = { "obs_names": (5,None), "obs": (5,None) }
observation_dict.sample(mask=mask)

{'obs_names': ('HBm6gJfm',
  'ICZg8IqLr8j1hgN0ivtGowQ7do7qWZ',
  't',
  'Dzc',
  'N5XpDYKzeiarVy1wypR9o'),
 'obs': (array([-0.13021018], dtype=float32),
  array([0.31126815], dtype=float32),
  array([-0.23990355], dtype=float32),
  array([-0.07092479], dtype=float32),
  array([-0.99374604], dtype=float32))}

In [12]:
observation_dict = spaces.Dict({})
observation_dict["obs_names"] = spaces.Sequence(spaces.Text(max_length=32))
observation_dict["obs"] = spaces.Sequence(spaces.Box(low=-1, high=1, shape=(2,2), dtype=np.float32))

In [13]:
mask = { "obs_names": (5,None), "obs": (5,None) }
observation_dict.sample(mask=mask)

{'obs_names': ('hHWBg55rgo4wcwaJY1sf',
  'ZL',
  'PrBCQiVcchea',
  'p3IOIsROe1SzXTw1icWiiSx9CUVLO',
  'PyK8RD6W5tu6jO4rJ7eXB6e4'),
 'obs': (array([[ 0.6543019 , -0.95828635],
         [-0.5836239 , -0.2220719 ]], dtype=float32),
  array([[ 0.13040282, -0.36425245],
         [-0.8024349 ,  0.38850486]], dtype=float32),
  array([[ 0.01062453,  0.6428043 ],
         [-0.64149976,  0.535741  ]], dtype=float32),
  array([[-0.96674407, -0.38587722],
         [ 0.11488003, -0.6347019 ]], dtype=float32),
  array([[-0.04374694, -0.39266613],
         [-0.63584036,  0.41252968]], dtype=float32))}