In [1]:

import gymnasium as gym
from gymnasium import spaces
import numpy as np

import bam_gym
from bam_gym.wrappers.mock_obs import MockObs
from bam_gym.utils import print_step, print_gym_space, print_reset, print_observation, print_action
from bam_gym.transport import MockTransport 

%reload_ext autoreload
%autoreload 2



In [2]:
env = gym.make("CartPole-v1")
env = MockObs(env)
print(env)
env.reset()
env.step(env.action_space.sample())

called!
<MockObs<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>>
called!
called!


(array([-3.8268769 ,  1.5464551 , -0.2668858 ,  0.97988486], dtype=float32),
 1.0,
 False,
 False,
 {})

In [ ]:
# The passive Env checker is nice to make sure that environment is compliant!
# It doesn't work with Transport though, as it can sometimes return empty observations!
# So its ok in development, but not in production.

env = gym.make("bam/GenericGymClient", disable_env_checker=True, transport=MockTransport(), n_pose=1)
env = MockObs(env)
print(env)
env = gym.wrappers.PassiveEnvChecker(env)
print(env)

print(env.action_space)
print(env.observation_space)
print_reset(*env.reset())
action = env.action_space.sample()
print_step(action, *env.step(env.action_space.sample()))

<MockObs<OrderEnforcing<GenericGymClient<bam/GenericGymClient>>>>
<PassiveEnvChecker<MockObs<OrderEnforcing<GenericGymClient<bam/GenericGymClient>>>>>
Discrete(1)
<MaskedSpace<Dict('pose_names': Sequence(Text(1, 32, charset=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz), stack=False), 'pose': Sequence(Dict('orientation': Dict('x': Box(-3.1415927, 3.1415927, (), float32), 'y': Box(-3.1415927, 3.1415927, (), float32), 'z': Box(-3.1415927, 3.1415927, (), float32)), 'position': Dict('x': Box(-10.0, 10.0, (), float32), 'y': Box(-10.0, 10.0, (), float32), 'z': Box(-10.0, 10.0, (), float32))), stack=False))>>

Reset Result:
    Observation : {'pose_names': ['AozSCFV6'], 'pose': [{'orientation': {'x': '2.1', 'y': '-1.9', 'z': '3.1'}, 'position': {'x': '3.2', 'y': '4.1', 'z': '-4.9'}}]}
    Info        : {'header': {'process_duration': 0.0, 'transport_duration': 0.0, 'error_code': {'value': 'FAILURE'}, 'error_msg': 'MockTransport: No server running, so no obs to return.', 'cali

In [181]:
env = gym.make("bam/GenericGymClient", disable_env_checker=True, transport=MockTransport(), n_pose=1)
print(env)

print(env.action_space)
print(env.observation_space)
print_reset(*env.reset())
action = env.action_space.sample()
print_step(action, *env.step(env.action_space.sample()))

<OrderEnforcing<GenericGymClient<bam/GenericGymClient>>>
Discrete(1)
<MaskedSpace<Dict('pose_names': Sequence(Text(1, 32, charset=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz), stack=False), 'pose': Sequence(Dict('orientation': Dict('x': Box(-3.1415927, 3.1415927, (), float32), 'y': Box(-3.1415927, 3.1415927, (), float32), 'z': Box(-3.1415927, 3.1415927, (), float32)), 'position': Dict('x': Box(-10.0, 10.0, (), float32), 'y': Box(-10.0, 10.0, (), float32), 'z': Box(-10.0, 10.0, (), float32))), stack=False))>>

Reset Result:
    Observation : {}
    Info        : {'header': {'process_duration': 0.0, 'transport_duration': 0.0, 'error_code': {'value': 'FAILURE'}, 'error_msg': 'MockTransport: No server running, so no obs to return.', 'calibrated': False, 'response_stamp': {'sec': 0, 'nanosec': 0}}}

[0] Step Result:
    Action      : 0
    Observation : {}
    Reward      : 0.0
    Terminated  : False
    Truncated   : False
    Info        : {'header': {'process_duration

In [ ]:

env.step(env.action_space.sample())

In [25]:
env = gym.make_vec("CartPole-v1")
env = MockObs(env)
print(env)

AssertionError: Expected env to be a `gymnasium.Env` but got <class 'gymnasium.envs.classic_control.cartpole.CartPoleVectorEnv'>

In [59]:
print(env.observation_space)
env.reset()
env.step(env.action_space.sample())

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)
Called
Called


(array([ 3.326965  , -0.01999814,  0.13210985, -0.8156009 ], dtype=float32),
 1.0,
 False,
 False,
 {})

In [ ]:
env = gym.make("CartPole-v1")
env = gym.wrappers.Autoreset(env)
print(env)

<Autoreset<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>>


In [64]:
env = gym.make_vec("CartPole-v1")
env = gym.wrappers.vector.Autoreset(env)
print(env)

AttributeError: module 'gymnasium.wrappers.vector' has no attribute 'Autoreset'

In [60]:
env = gym.make_vec("CartPole-v1")
env = MockObs(env)
print(env)

AssertionError: Expected env to be a `gymnasium.Env` but got <class 'gymnasium.envs.classic_control.cartpole.CartPoleVectorEnv'>

Called


(array([-4.0382977 , -0.8276858 , -0.285829  ,  0.24939997], dtype=float32),
 1.0,
 False,
 False,
 {})